site_name: Synthese

use_directory_urls: false

theme:
    name: mkdocs

nav:
    - Imaginer: 1.imaginer.md
    - Concevoir: 2.concevoir_planifier.md
    - Collecter: 3.collecter.md
    - Traiter: 4.traiter.md
    - Analyser: 5.analyser.md
    - Archiver: 6.archiver.md
    - Publier: 7.publier.md
    - Conclusion Bibliographie: 8.conclusion.md
    - Annexe 1: 98. Infrastructures.md
    - Annexe 2: 99. Reproductibilit√©.md 

lang:
    default: ['fr']

markdown_extensions:
    - footnotes

plugins:
    - search
    - enumerate-headings:
